# Site settings

title: BETA | Nick Zuber | Software Engineer
email: zuber.nicholas@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Nick Zuber is a sofware engineer for the web and mobile applications based out of the Boston area.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://localhost:4000"

twitter_username: nick_zuber
github_username:  nickzuber
full_name: Nick Zuber

npm_stats: 10181

job_title: Software Engineer Intern
job_segue: at
job_place: Box

permalink: /:categories/:title

# Build settings
markdown: kramdown
source: src
destination: public

gems:
- octopress-minify-html

sass:
  style: :compressed

# FOR DEV WE EXCLUDE POSTS TO SPEED UP COMPILE TIME
exclude:
- node_modules
- package.json
- _drafts
- _posts
